apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 80
  selector:
    app: client
status:
  loadBalancer: {}
